# Generated by Django 5.2.8 on 2025-12-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='descarga.jpg', null=True, upload_to='Profile_Images'),
        ),
    ]
